.PHONY: build test check
build:
	go build -trimpath -o bin/ ./cmd/...
test:
	go test -race ./...
check:
	python3 -m unittest discover -s internal/images -p '*_test.py'
	@test -z "$$(gofmt -l cmd internal)" || (gofmt -l cmd internal; exit 1)
	go vet ./...
	go test -race ./...
